using System;
using System.Threading;
using Cysharp.Threading.Tasks;

namespace Caliburn.Noesis
{
    /// <summary>
    /// Represents an asynchronous event handler.
    /// </summary>
    /// <typeparam name="TEventArgs">The type of the event data generated by the event.</typeparam>
    /// <param name="sender">The source of the event.</param>
    /// <param name="e">An object that contains the event data.</param>
    /// <param name="cancellationToken">(Optional) The cancellation token to cancel operation.</param>
    /// <returns>A task that represents the asynchronous operation.</returns>
    public delegate UniTask AsyncEventHandler<TEventArgs>(
        object sender,
        TEventArgs e,
        CancellationToken cancellationToken = default)
        where TEventArgs : EventArgs;
}
