namespace Caliburn.Noesis
{
    using System;
    using System.Threading;
    using Cysharp.Threading.Tasks;

    /// <summary>Represents the asynchronous method that will handle an event when the event provides data.</summary>
    /// <typeparam name="TEventArgs">The type of the event data generated by the event.</typeparam>
    /// <param name="sender">The source of the event.</param>
    /// <param name="e">An object that contains the event data.</param>
    /// <param name="cancellationToken">(Optional) The cancellation token to cancel operation.</param>
    public delegate UniTask AsyncEventHandler<in TEventArgs>(object sender,
                                                             TEventArgs e,
                                                             CancellationToken cancellationToken = default)
        where TEventArgs : EventArgs;
}